---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mysql-operator
  namespace: mysql-operator
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: mysql-operator
      version: '2.1.3'
      sourceRef:
        kind: HelmRepository
        name: mysql-operator
      interval: 5m
  releaseName: mysql-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values: