apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: snorlax-user
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Example ACL rules for producing to topic my-topic
      - resource:
          type: topic
          name: test
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
          - Delete
        host: "*"