---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
  namespace: kafka
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: '0.40.0'
      sourceRef:
        kind: HelmRepository
        name: strimzi
      interval: 5m
  releaseName: strimzi-kafka-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    replicaCount: 2